---
# tasks file for tomcat- name: Install Java 8 CentOS
- name: Install Java 8 CentOs
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Ajout du groupe tomcat 
  group:
    name: tomcat

- name: Ajout de l'user "tomcat" 
  user:
    name: tomcat
    group: tomcat
    home: /opt/tomcat
    createhome: no
    system: yes

- name: Création du répéprtoire tomcat 
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    
- name: Téléchargement de  Tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
    dest: /home/adm1 

- name: Extract tomcat archive
  unarchive:
    src: /home/adm1/apache-tomcat-10.0.27.tar.gz 
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    

- name: Création du tomcat.service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: Start tomcat avec enable 
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes

- name: Open tomcat port on the firewall
  firewalld:
    port: "{{ Port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
- name: Définition du Port
  template:
    src: server.xml.j2
    dest: /opt/tomcat/apache-tomcat-10.0.27/conf/server.xml
  
- name: Set UI access credentials
  template:
    src: tomcat-users.xml.j2
    dest: /opt/tomcat/apache-tomcat-10.0.27/conf/tomcat-users.xml
  
- name: Autorisation de l'accès aux applications Manager et Host Manager à partir de n'importe quelle adresse IP
  template:
    src: context.xml.j2 
    dest: "{{ item }}"
  with_items:
    - /opt/tomcat/apache-tomcat-10.0.27/webapps/host-manager/META-INF/context.xml
    - /opt/tomcat/apache-tomcat-10.0.27/webapps/manager/META-INF/context.xml
  notify: reload_tomcat
  

